org: fmmarchand
app: swapi-randomizer
service: character-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  apiGateway:
    shouldStartNameWithService: true

functions:
  getPeople:
    handler: src/handlers/people/getPeople.getPeopleHandler
    events:
      - http:
          path: myswapi/{id}
          method: get
          cors: true
  createCharacter:
    handler: src/handlers/people/createCharacter.createCharacterHandler
    events:
      - http:
          path: myswapi
          method: post
          cors: true

plugins:
  - serverless-offline
