org: fmmarchand
app: swapi-randomizer
service: character-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  apiGateway:
    shouldStartNameWithService: true

functions:
  findOneCharacter:
    handler: src/handlers/people/findOneCharacter.findOneCharacterHandler
    events:
      - http:
          path: character/{id}
          method: get
          cors: true
  createCharacter:
    handler: src/handlers/character/createCharacter.createCharacterHandler
    events:
      - http:
          path: character
          method: post
          cors: true
  getPeople:
    handler: src/handlers/people/getPeople.getPeopleHandler
    events:
      - http:
          path: myswapi/{id}
          method: get
          cors: true

resources:
  Resources:
    CharactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Characters
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-offline
